/* --------------------------------------------------------------------------
   Master Real Categories Tree Database (Extracted from Tiendanube CSV)
   Auto-generated by scripts/sync_categories.py
   -------------------------------------------------------------------------- */

const REAL_CATEGORIES_TREE = [
  {
    "id": "agua",
    "name": "AGUA",
    "displayName": "Agua",
    "description": "Electrobombas centrífugas, presurizadoras, sumergibles y bombas solares.",
    "count": 19,
    "subcategoriesCount": 2,
    "subcategories": [
      {
        "name": "BOMBA SUPERFICIE",
        "displayName": "Bomba Superficie",
        "count": 10,
        "slug": "bomba-superficie",
        "subsubcategories": [
          {
            "name": "Bombas Centrifugas",
            "count": 2,
            "slug": "bombas-centrifugas"
          },
          {
            "name": "Bombas Para Pileta",
            "count": 2,
            "slug": "bombas-para-pileta"
          },
          {
            "name": "Bombas Perifericas",
            "count": 3,
            "slug": "bombas-perifericas"
          },
          {
            "name": "Bombas Presurizadoras",
            "count": 2,
            "slug": "bombas-presurizadoras"
          },
          {
            "name": "Electrobombas Autocebantes",
            "count": 1,
            "slug": "electrobombas-autocebantes"
          }
        ]
      },
      {
        "name": "BOMBAS SUMERGIBLES",
        "displayName": "Bombas Sumergibles",
        "count": 9,
        "slug": "bombas-sumergibles",
        "subsubcategories": [
          {
            "name": "Bombas Desagote",
            "count": 6,
            "slug": "bombas-desagote"
          },
          {
            "name": "Electrobomba Solar",
            "count": 2,
            "slug": "electrobomba-solar"
          },
          {
            "name": "Electrobombas",
            "count": 1,
            "slug": "electrobombas"
          }
        ]
      }
    ]
  },
  {
    "id": "construccion",
    "name": "CONSTRUCCION",
    "displayName": "Construcción",
    "description": "Compactación, cortadoras de concreto, allanadoras, medición láser y demolición.",
    "count": 151,
    "subcategoriesCount": 11,
    "subcategories": [
      {
        "name": "ACCESORIOS E INSUMOS",
        "displayName": "Accesorios e Insumos",
        "count": 34,
        "slug": "accesorios-e-insumos",
        "subsubcategories": [
          {
            "name": "Ahoyadora Y Mechas Husq.",
            "count": 4,
            "slug": "ahoyadora-y-mechas-husq"
          },
          {
            "name": "Cabezal Vibrador",
            "count": 6,
            "slug": "cabezal-vibrador"
          },
          {
            "name": "Cinceles Y Puntas",
            "count": 12,
            "slug": "cinceles-y-puntas"
          },
          {
            "name": "Disco Llaneado",
            "count": 6,
            "slug": "disco-llaneado"
          },
          {
            "name": "Llanas",
            "count": 5,
            "slug": "llanas"
          },
          {
            "name": "Mechas P/Ahoyadoras Niwa",
            "count": 1,
            "slug": "mechas-p-ahoyadoras-niwa"
          }
        ]
      },
      {
        "name": "ALLANADORA",
        "displayName": "Allanadora",
        "count": 1,
        "slug": "allanadora",
        "subsubcategories": [
          {
            "name": "Llanas",
            "count": 1,
            "slug": "llanas"
          }
        ]
      },
      {
        "name": "COMPACTACION",
        "displayName": "Compactacion",
        "count": 21,
        "slug": "compactacion",
        "subsubcategories": [
          {
            "name": "Motopisones",
            "count": 6,
            "slug": "motopisones"
          },
          {
            "name": "Plancha Compactadora",
            "count": 8,
            "slug": "plancha-compactadora"
          },
          {
            "name": "Rodillo Compactador",
            "count": 7,
            "slug": "rodillo-compactador"
          }
        ]
      },
      {
        "name": "CORTADORA CONCRETO",
        "displayName": "Cortadora Concreto",
        "count": 9,
        "slug": "cortadora-concreto",
        "subsubcategories": [
          {
            "name": "Cortadora Manual",
            "count": 3,
            "slug": "cortadora-manual"
          },
          {
            "name": "Cortadoras",
            "count": 6,
            "slug": "cortadoras"
          }
        ]
      },
      {
        "name": "HERRAMIENTA ELECTRICA CONST.",
        "displayName": "Herramienta Electrica Const.",
        "count": 2,
        "slug": "herramienta-electrica-const",
        "subsubcategories": [
          {
            "name": "Martillo Rotopercutor",
            "count": 1,
            "slug": "martillo-rotopercutor"
          },
          {
            "name": "Rotomartillo Elect Const",
            "count": 1,
            "slug": "rotomartillo-elect-const"
          }
        ]
      },
      {
        "name": "MEDICION",
        "displayName": "Medicion",
        "count": 25,
        "slug": "medicion",
        "subsubcategories": [
          {
            "name": "Cinta Metrica",
            "count": 1,
            "slug": "cinta-metrica"
          },
          {
            "name": "Medidor Laser",
            "count": 5,
            "slug": "medidor-laser"
          },
          {
            "name": "Nivel Laser",
            "count": 12,
            "slug": "nivel-laser"
          },
          {
            "name": "Nivel Manual",
            "count": 7,
            "slug": "nivel-manual"
          }
        ]
      },
      {
        "name": "PERFORADORA",
        "displayName": "Perforadora",
        "count": 3,
        "slug": "perforadora",
        "subsubcategories": [
          {
            "name": "Broca Construccion",
            "count": 3,
            "slug": "broca-construccion"
          }
        ]
      },
      {
        "name": "PREPARACION DE CONCRETO",
        "displayName": "Preparacion De Concreto",
        "count": 13,
        "slug": "preparacion-de-concreto",
        "subsubcategories": [
          {
            "name": "Baldes De Albañil",
            "count": 1,
            "slug": "baldes-de-alba-il"
          },
          {
            "name": "Hormigonera",
            "count": 12,
            "slug": "hormigonera"
          }
        ]
      },
      {
        "name": "SEGURIDAD",
        "displayName": "Seguridad",
        "count": 10,
        "slug": "seguridad",
        "subsubcategories": [
          {
            "name": "Andamios",
            "count": 7,
            "slug": "andamios"
          },
          {
            "name": "Caballetes",
            "count": 1,
            "slug": "caballetes"
          },
          {
            "name": "Tablones",
            "count": 2,
            "slug": "tablones"
          }
        ]
      },
      {
        "name": "Superficie y pulido",
        "displayName": "Superficie y Pulido",
        "count": 2,
        "slug": "superficie-y-pulido",
        "subsubcategories": [
          {
            "name": "Escarificadoras E Insumos",
            "count": 1,
            "slug": "escarificadoras-e-insumos"
          },
          {
            "name": "Mesa De Corte De Cerámica",
            "count": 1,
            "slug": "mesa-de-corte-de-cer-mica"
          }
        ]
      },
      {
        "name": "TERMINADO DE CONCRETO",
        "displayName": "Terminado De Concreto",
        "count": 31,
        "slug": "terminado-de-concreto",
        "subsubcategories": [
          {
            "name": "Allanadoras - Alisadoras",
            "count": 16,
            "slug": "allanadoras-alisadoras"
          },
          {
            "name": "Fratacho",
            "count": 4,
            "slug": "fratacho"
          },
          {
            "name": "Regla Manual",
            "count": 1,
            "slug": "regla-manual"
          },
          {
            "name": "Regla Vibratoria",
            "count": 6,
            "slug": "regla-vibratoria"
          },
          {
            "name": "Vibrador Electrico",
            "count": 3,
            "slug": "vibrador-electrico"
          },
          {
            "name": "Vibrador Explosion",
            "count": 1,
            "slug": "vibrador-explosion"
          }
        ]
      }
    ]
  },
  {
    "id": "consumibles-e-insumos",
    "name": "CONSUMIBLES E INSUMOS",
    "displayName": "Consumibles e Insumos",
    "description": "Cadenas, espadas, tanzas, aceites 2T y 4T, grasas y lubricantes específicos.",
    "count": 82,
    "subcategoriesCount": 5,
    "subcategories": [
      {
        "name": "BORDEADORA",
        "displayName": "Bordeadora",
        "count": 2,
        "slug": "bordeadora",
        "subsubcategories": [
          {
            "name": "Tanza",
            "count": 2,
            "slug": "tanza"
          }
        ]
      },
      {
        "name": "DESMALEZADORA",
        "displayName": "Desmalezadora",
        "count": 13,
        "slug": "desmalezadora",
        "subsubcategories": [
          {
            "name": "Tanza",
            "count": 13,
            "slug": "tanza"
          }
        ]
      },
      {
        "name": "HERRAMIENTA",
        "displayName": "Herramienta",
        "count": 7,
        "slug": "herramienta",
        "subsubcategories": [
          {
            "name": "Limas",
            "count": 3,
            "slug": "limas"
          },
          {
            "name": "Portalima",
            "count": 3,
            "slug": "portalima"
          },
          {
            "name": "Yunque",
            "count": 1,
            "slug": "yunque"
          }
        ]
      },
      {
        "name": "LUBRICANTE",
        "displayName": "Lubricante",
        "count": 26,
        "slug": "lubricante",
        "subsubcategories": [
          {
            "name": "Aceite",
            "count": 22,
            "slug": "aceite"
          },
          {
            "name": "Grasa",
            "count": 4,
            "slug": "grasa"
          }
        ]
      },
      {
        "name": "MOTOSIERRA",
        "displayName": "Motosierra",
        "count": 34,
        "slug": "motosierra",
        "subsubcategories": [
          {
            "name": "Cadena",
            "count": 33,
            "slug": "cadena"
          },
          {
            "name": "Eslabon",
            "count": 1,
            "slug": "eslabon"
          }
        ]
      }
    ]
  },
  {
    "id": "ferreteria",
    "name": "FERRETERIA",
    "displayName": "Ferretería",
    "description": "Herramientas manuales, eléctricas, a batería, neumáticas y equipamiento para taller.",
    "count": 1192,
    "subcategoriesCount": 13,
    "subcategories": [
      {
        "name": "ACCESORIO E INSUMOS",
        "displayName": "Accesorio e Insumos",
        "count": 340,
        "slug": "accesorio-e-insumos",
        "subsubcategories": [
          {
            "name": "Abrazaderas",
            "count": 3,
            "slug": "abrazaderas"
          },
          {
            "name": "Adaptadores",
            "count": 11,
            "slug": "adaptadores"
          },
          {
            "name": "Aerografo",
            "count": 1,
            "slug": "aerografo"
          },
          {
            "name": "Alambre Soldadora",
            "count": 6,
            "slug": "alambre-soldadora"
          },
          {
            "name": "Antiadherentes Para Soldadoras",
            "count": 1,
            "slug": "antiadherentes-para-soldadoras"
          },
          {
            "name": "Bidon",
            "count": 8,
            "slug": "bidon"
          },
          {
            "name": "Bombas Aguas P/ Taladros",
            "count": 2,
            "slug": "bombas-aguas-p-taladros"
          },
          {
            "name": "Broca",
            "count": 5,
            "slug": "broca"
          },
          {
            "name": "Caballete",
            "count": 1,
            "slug": "caballete"
          },
          {
            "name": "Cable Bateria",
            "count": 1,
            "slug": "cable-bateria"
          },
          {
            "name": "Cabo Madera",
            "count": 1,
            "slug": "cabo-madera"
          },
          {
            "name": "Caja De Herramientas",
            "count": 1,
            "slug": "caja-de-herramientas"
          },
          {
            "name": "Cepillo Acero",
            "count": 2,
            "slug": "cepillo-acero"
          },
          {
            "name": "Cepillo Circular",
            "count": 2,
            "slug": "cepillo-circular"
          },
          {
            "name": "Cepillo De Copa",
            "count": 1,
            "slug": "cepillo-de-copa"
          },
          {
            "name": "Cincha",
            "count": 1,
            "slug": "cincha"
          },
          {
            "name": "Cintas Aislantes",
            "count": 2,
            "slug": "cintas-aislantes"
          },
          {
            "name": "Clavos",
            "count": 13,
            "slug": "clavos"
          },
          {
            "name": "Cuenta Litros",
            "count": 2,
            "slug": "cuenta-litros"
          },
          {
            "name": "Discos Corte Y Abrasivos",
            "count": 116,
            "slug": "discos-corte-y-abrasivos"
          },
          {
            "name": "Empuñadura",
            "count": 3,
            "slug": "empu-adura"
          },
          {
            "name": "Fresas",
            "count": 5,
            "slug": "fresas"
          },
          {
            "name": "Guarda",
            "count": 1,
            "slug": "guarda"
          },
          {
            "name": "Hoja De Sierra",
            "count": 15,
            "slug": "hoja-de-sierra"
          },
          {
            "name": "Hojas De Calar",
            "count": 3,
            "slug": "hojas-de-calar"
          },
          {
            "name": "Kit Compresor",
            "count": 1,
            "slug": "kit-compresor"
          },
          {
            "name": "Kit De Corte",
            "count": 1,
            "slug": "kit-de-corte"
          },
          {
            "name": "Lijas",
            "count": 22,
            "slug": "lijas"
          },
          {
            "name": "Mallas Y Cintas",
            "count": 2,
            "slug": "mallas-y-cintas"
          },
          {
            "name": "Mandril",
            "count": 4,
            "slug": "mandril"
          },
          {
            "name": "Mechas",
            "count": 56,
            "slug": "mechas"
          },
          {
            "name": "Mesa",
            "count": 1,
            "slug": "mesa"
          },
          {
            "name": "Morsa",
            "count": 3,
            "slug": "morsa"
          },
          {
            "name": "Picos Surtidores",
            "count": 1,
            "slug": "picos-surtidores"
          },
          {
            "name": "Piedra Afilar",
            "count": 2,
            "slug": "piedra-afilar"
          },
          {
            "name": "Piedra De Amolar",
            "count": 2,
            "slug": "piedra-de-amolar"
          },
          {
            "name": "Pinza Sujeccion",
            "count": 1,
            "slug": "pinza-sujeccion"
          },
          {
            "name": "Pistola Combustible",
            "count": 1,
            "slug": "pistola-combustible"
          },
          {
            "name": "Plato Apoyo",
            "count": 1,
            "slug": "plato-apoyo"
          },
          {
            "name": "Puntas",
            "count": 5,
            "slug": "puntas"
          },
          {
            "name": "Reflector",
            "count": 2,
            "slug": "reflector"
          },
          {
            "name": "Remaches",
            "count": 4,
            "slug": "remaches"
          },
          {
            "name": "Router",
            "count": 1,
            "slug": "router"
          },
          {
            "name": "Ruedas",
            "count": 4,
            "slug": "ruedas"
          },
          {
            "name": "Sierra Copa",
            "count": 8,
            "slug": "sierra-copa"
          },
          {
            "name": "Siliconas",
            "count": 1,
            "slug": "siliconas"
          },
          {
            "name": "Soga",
            "count": 7,
            "slug": "soga"
          },
          {
            "name": "Tarugos Madera",
            "count": 1,
            "slug": "tarugos-madera"
          },
          {
            "name": "Terminales De Baterias",
            "count": 1,
            "slug": "terminales-de-baterias"
          }
        ]
      },
      {
        "name": "ACCESORIO GAS BRONCE",
        "displayName": "Accesorio Gas Bronce",
        "count": 2,
        "slug": "accesorio-gas-bronce",
        "subsubcategories": [
          {
            "name": "Buje",
            "count": 2,
            "slug": "buje"
          }
        ]
      },
      {
        "name": "CLIMATIZACION",
        "displayName": "Climatizacion",
        "count": 7,
        "slug": "climatizacion",
        "subsubcategories": [
          {
            "name": "Calefactor",
            "count": 5,
            "slug": "calefactor"
          },
          {
            "name": "Calefactor A Gas",
            "count": 2,
            "slug": "calefactor-a-gas"
          }
        ]
      },
      {
        "name": "EQUIPOS PESADOS",
        "displayName": "Equipos Pesados",
        "count": 17,
        "slug": "equipos-pesados",
        "subsubcategories": [
          {
            "name": "Criquets",
            "count": 10,
            "slug": "criquets"
          },
          {
            "name": "Destalonadoras",
            "count": 2,
            "slug": "destalonadoras"
          },
          {
            "name": "Elevadores De Autos",
            "count": 1,
            "slug": "elevadores-de-autos"
          },
          {
            "name": "Guinches",
            "count": 2,
            "slug": "guinches"
          },
          {
            "name": "Prensas",
            "count": 2,
            "slug": "prensas"
          }
        ]
      },
      {
        "name": "HERRAMIENTA NEUMATICA",
        "displayName": "Herramienta Neumatica",
        "count": 51,
        "slug": "herramienta-neumatica",
        "subsubcategories": [
          {
            "name": "Accesorios E Insumos",
            "count": 1,
            "slug": "accesorios-e-insumos"
          },
          {
            "name": "Amoladora Neumatica",
            "count": 2,
            "slug": "amoladora-neumatica"
          },
          {
            "name": "Arenador",
            "count": 1,
            "slug": "arenador"
          },
          {
            "name": "Atornillador Neumatico",
            "count": 1,
            "slug": "atornillador-neumatico"
          },
          {
            "name": "Bomba Engrase",
            "count": 3,
            "slug": "bomba-engrase"
          },
          {
            "name": "Clavadoras",
            "count": 4,
            "slug": "clavadoras"
          },
          {
            "name": "Compresor A Bateria",
            "count": 9,
            "slug": "compresor-a-bateria"
          },
          {
            "name": "Compresor Silencioso",
            "count": 5,
            "slug": "compresor-silencioso"
          },
          {
            "name": "Compresores A Correa",
            "count": 11,
            "slug": "compresores-a-correa"
          },
          {
            "name": "Compresores De Alta Recuperacion",
            "count": 7,
            "slug": "compresores-de-alta-recuperacion"
          },
          {
            "name": "Kit Compresor",
            "count": 2,
            "slug": "kit-compresor"
          },
          {
            "name": "Lijadoras",
            "count": 1,
            "slug": "lijadoras"
          },
          {
            "name": "Llave De Impacto",
            "count": 4,
            "slug": "llave-de-impacto"
          }
        ]
      },
      {
        "name": "HERRAMIENTAS A BATERIA",
        "displayName": "Herramientas A Bateria",
        "count": 132,
        "slug": "herramientas-a-bateria",
        "subsubcategories": [
          {
            "name": "Accesorios E Insumos",
            "count": 1,
            "slug": "accesorios-e-insumos"
          },
          {
            "name": "Amoladoras",
            "count": 19,
            "slug": "amoladoras"
          },
          {
            "name": "Atornillador A Bateria",
            "count": 17,
            "slug": "atornillador-a-bateria"
          },
          {
            "name": "Cepillos Para Madera",
            "count": 1,
            "slug": "cepillos-para-madera"
          },
          {
            "name": "Clavadora",
            "count": 3,
            "slug": "clavadora"
          },
          {
            "name": "Herramientas Especiales",
            "count": 12,
            "slug": "herramientas-especiales"
          },
          {
            "name": "Iluminacion",
            "count": 10,
            "slug": "iluminacion"
          },
          {
            "name": "Lijadora",
            "count": 10,
            "slug": "lijadora"
          },
          {
            "name": "Lijadora Orbital",
            "count": 1,
            "slug": "lijadora-orbital"
          },
          {
            "name": "Llave De Impacto",
            "count": 14,
            "slug": "llave-de-impacto"
          },
          {
            "name": "Martillo Demoledor",
            "count": 3,
            "slug": "martillo-demoledor"
          },
          {
            "name": "Multiuso A Bateria",
            "count": 3,
            "slug": "multiuso-a-bateria"
          },
          {
            "name": "Pulidora",
            "count": 2,
            "slug": "pulidora"
          },
          {
            "name": "Sierra",
            "count": 14,
            "slug": "sierra"
          },
          {
            "name": "Taladros",
            "count": 23,
            "slug": "taladros"
          }
        ]
      },
      {
        "name": "HERRAMIENTAS ELECTRICAS",
        "displayName": "Herramientas Electricas",
        "count": 268,
        "slug": "herramientas-electricas",
        "subsubcategories": [
          {
            "name": "Acanaladoras",
            "count": 1,
            "slug": "acanaladoras"
          },
          {
            "name": "Accesorios E Insumos",
            "count": 17,
            "slug": "accesorios-e-insumos"
          },
          {
            "name": "Afilador Cadenas",
            "count": 4,
            "slug": "afilador-cadenas"
          },
          {
            "name": "Amoladoras",
            "count": 38,
            "slug": "amoladoras"
          },
          {
            "name": "Atornilladores Eléctricos",
            "count": 3,
            "slug": "atornilladores-el-ctricos"
          },
          {
            "name": "Cargador",
            "count": 18,
            "slug": "cargador"
          },
          {
            "name": "Cepilladora",
            "count": 3,
            "slug": "cepilladora"
          },
          {
            "name": "Cortadora",
            "count": 10,
            "slug": "cortadora"
          },
          {
            "name": "Electrobombas Para Trasvase De Combustible",
            "count": 9,
            "slug": "electrobombas-para-trasvase-de-combustible"
          },
          {
            "name": "Equipo De Pintar",
            "count": 1,
            "slug": "equipo-de-pintar"
          },
          {
            "name": "Fresadoras",
            "count": 3,
            "slug": "fresadoras"
          },
          {
            "name": "Herramientas Especiales",
            "count": 20,
            "slug": "herramientas-especiales"
          },
          {
            "name": "Lijadora",
            "count": 19,
            "slug": "lijadora"
          },
          {
            "name": "Llave De Impacto",
            "count": 1,
            "slug": "llave-de-impacto"
          },
          {
            "name": "Martillo Demoledor",
            "count": 24,
            "slug": "martillo-demoledor"
          },
          {
            "name": "Minitorno",
            "count": 1,
            "slug": "minitorno"
          },
          {
            "name": "Perforadoras",
            "count": 4,
            "slug": "perforadoras"
          },
          {
            "name": "Pulidora",
            "count": 3,
            "slug": "pulidora"
          },
          {
            "name": "Sierra",
            "count": 27,
            "slug": "sierra"
          },
          {
            "name": "Sierras Sin Fin",
            "count": 2,
            "slug": "sierras-sin-fin"
          },
          {
            "name": "Soldadoras",
            "count": 32,
            "slug": "soldadoras"
          },
          {
            "name": "Taladros",
            "count": 26,
            "slug": "taladros"
          },
          {
            "name": "Termofusoras Electricas",
            "count": 2,
            "slug": "termofusoras-electricas"
          }
        ]
      },
      {
        "name": "HERRAMIENTAS MANUALES",
        "displayName": "Herramientas Manuales",
        "count": 193,
        "slug": "herramientas-manuales",
        "subsubcategories": [
          {
            "name": "Alicate",
            "count": 9,
            "slug": "alicate"
          },
          {
            "name": "Arco Sierra",
            "count": 1,
            "slug": "arco-sierra"
          },
          {
            "name": "Azada",
            "count": 2,
            "slug": "azada"
          },
          {
            "name": "Bombas De Trasvase",
            "count": 1,
            "slug": "bombas-de-trasvase"
          },
          {
            "name": "Carro De Aluminio",
            "count": 1,
            "slug": "carro-de-aluminio"
          },
          {
            "name": "Cinta Metrica",
            "count": 1,
            "slug": "cinta-metrica"
          },
          {
            "name": "Cuchillos",
            "count": 3,
            "slug": "cuchillos"
          },
          {
            "name": "Cutter",
            "count": 1,
            "slug": "cutter"
          },
          {
            "name": "Destornillador",
            "count": 2,
            "slug": "destornillador"
          },
          {
            "name": "Escardillo",
            "count": 2,
            "slug": "escardillo"
          },
          {
            "name": "Graseras Engrasadoras",
            "count": 5,
            "slug": "graseras-engrasadoras"
          },
          {
            "name": "Hacha",
            "count": 3,
            "slug": "hacha"
          },
          {
            "name": "Herramientas Especiales",
            "count": 30,
            "slug": "herramientas-especiales"
          },
          {
            "name": "Kit De Herramientas",
            "count": 27,
            "slug": "kit-de-herramientas"
          },
          {
            "name": "Limas",
            "count": 8,
            "slug": "limas"
          },
          {
            "name": "Llaves",
            "count": 35,
            "slug": "llaves"
          },
          {
            "name": "Maza Y  Martillos",
            "count": 5,
            "slug": "maza-y-martillos"
          },
          {
            "name": "Medicion",
            "count": 3,
            "slug": "medicion"
          },
          {
            "name": "Navaja",
            "count": 1,
            "slug": "navaja"
          },
          {
            "name": "Nivel Optico",
            "count": 1,
            "slug": "nivel-optico"
          },
          {
            "name": "Palas",
            "count": 19,
            "slug": "palas"
          },
          {
            "name": "Pico",
            "count": 1,
            "slug": "pico"
          },
          {
            "name": "Pinza",
            "count": 15,
            "slug": "pinza"
          },
          {
            "name": "Pistola De Pintura",
            "count": 3,
            "slug": "pistola-de-pintura"
          },
          {
            "name": "Puntas",
            "count": 1,
            "slug": "puntas"
          },
          {
            "name": "Set De Llaves Hexagonal",
            "count": 1,
            "slug": "set-de-llaves-hexagonal"
          },
          {
            "name": "Sierra",
            "count": 1,
            "slug": "sierra"
          },
          {
            "name": "Tenaza",
            "count": 4,
            "slug": "tenaza"
          },
          {
            "name": "Terraja",
            "count": 1,
            "slug": "terraja"
          }
        ]
      },
      {
        "name": "INDUMENTARIA SEGURIDAD",
        "displayName": "Indumentaria Seguridad",
        "count": 6,
        "slug": "indumentaria-seguridad",
        "subsubcategories": [
          {
            "name": "Calzado Seguridad",
            "count": 3,
            "slug": "calzado-seguridad"
          },
          {
            "name": "Pantalon",
            "count": 3,
            "slug": "pantalon"
          }
        ]
      },
      {
        "name": "MOVIMIENTO DE CARGA",
        "displayName": "Movimiento De Carga",
        "count": 18,
        "slug": "movimiento-de-carga",
        "subsubcategories": [
          {
            "name": "Aparejo",
            "count": 6,
            "slug": "aparejo"
          },
          {
            "name": "Carretillas",
            "count": 6,
            "slug": "carretillas"
          },
          {
            "name": "Carros Plegables",
            "count": 1,
            "slug": "carros-plegables"
          },
          {
            "name": "Transpallets",
            "count": 5,
            "slug": "transpallets"
          }
        ]
      },
      {
        "name": "ORGANIZACIÓN Y ALMACENAMIENTO",
        "displayName": "Organización y Almacenamiento",
        "count": 42,
        "slug": "organizaci-n-y-almacenamiento",
        "subsubcategories": [
          {
            "name": "Bolso",
            "count": 6,
            "slug": "bolso"
          },
          {
            "name": "Caja De Herramientas",
            "count": 29,
            "slug": "caja-de-herramientas"
          },
          {
            "name": "Carrito Plegables",
            "count": 1,
            "slug": "carrito-plegables"
          },
          {
            "name": "Escaleras",
            "count": 6,
            "slug": "escaleras"
          }
        ]
      },
      {
        "name": "RECREACION Y CAMPING",
        "displayName": "Recreacion y Camping",
        "count": 56,
        "slug": "recreacion-y-camping",
        "subsubcategories": [
          {
            "name": "Botellas",
            "count": 5,
            "slug": "botellas"
          },
          {
            "name": "Conservadora",
            "count": 2,
            "slug": "conservadora"
          },
          {
            "name": "Mate",
            "count": 15,
            "slug": "mate"
          },
          {
            "name": "Termos",
            "count": 21,
            "slug": "termos"
          },
          {
            "name": "Vasos",
            "count": 13,
            "slug": "vasos"
          }
        ]
      },
      {
        "name": "SEGURIDAD Y PROTECCION",
        "displayName": "Seguridad y Proteccion",
        "count": 60,
        "slug": "seguridad-y-proteccion",
        "subsubcategories": [
          {
            "name": "Antiparras Y Anteojos",
            "count": 7,
            "slug": "antiparras-y-anteojos"
          },
          {
            "name": "Arnes Desmalezadora",
            "count": 1,
            "slug": "arnes-desmalezadora"
          },
          {
            "name": "Arnes Seguridad",
            "count": 2,
            "slug": "arnes-seguridad"
          },
          {
            "name": "Cabo De Vida",
            "count": 2,
            "slug": "cabo-de-vida"
          },
          {
            "name": "Cascos",
            "count": 2,
            "slug": "cascos"
          },
          {
            "name": "Cincha",
            "count": 3,
            "slug": "cincha"
          },
          {
            "name": "Delantales",
            "count": 1,
            "slug": "delantales"
          },
          {
            "name": "Eslingas",
            "count": 2,
            "slug": "eslingas"
          },
          {
            "name": "Faja",
            "count": 3,
            "slug": "faja"
          },
          {
            "name": "Filtro",
            "count": 6,
            "slug": "filtro"
          },
          {
            "name": "Guante",
            "count": 8,
            "slug": "guante"
          },
          {
            "name": "Kit Proteccion",
            "count": 1,
            "slug": "kit-proteccion"
          },
          {
            "name": "Mameluco",
            "count": 1,
            "slug": "mameluco"
          },
          {
            "name": "Mascara Facial",
            "count": 13,
            "slug": "mascara-facial"
          },
          {
            "name": "Mascaras Soldar",
            "count": 5,
            "slug": "mascaras-soldar"
          },
          {
            "name": "Protector Auditivo",
            "count": 3,
            "slug": "protector-auditivo"
          }
        ]
      }
    ]
  },
  {
    "id": "generacion-energia",
    "name": "GENERACION ENERGIA",
    "displayName": "Generación Energía",
    "description": "Grupos electrógenos monofásicos y trifásicos, paneles solares e inversores.",
    "count": 112,
    "subcategoriesCount": 2,
    "subcategories": [
      {
        "name": "ENERGIA SOLAR",
        "displayName": "Energia Solar",
        "count": 59,
        "slug": "energia-solar",
        "subsubcategories": [
          {
            "name": "Accesorios",
            "count": 15,
            "slug": "accesorios"
          },
          {
            "name": "Baterias",
            "count": 5,
            "slug": "baterias"
          },
          {
            "name": "Electrificador Solar",
            "count": 2,
            "slug": "electrificador-solar"
          },
          {
            "name": "Inversor",
            "count": 13,
            "slug": "inversor"
          },
          {
            "name": "Panel Solar",
            "count": 13,
            "slug": "panel-solar"
          },
          {
            "name": "Soportes Y Montajes",
            "count": 7,
            "slug": "soportes-y-montajes"
          },
          {
            "name": "Termotanques",
            "count": 4,
            "slug": "termotanques"
          }
        ]
      },
      {
        "name": "GENERADOR",
        "displayName": "Generador",
        "count": 53,
        "slug": "generador",
        "subsubcategories": [
          {
            "name": "Estacion De Energia",
            "count": 5,
            "slug": "estacion-de-energia"
          },
          {
            "name": "Generador Insonorizado",
            "count": 11,
            "slug": "generador-insonorizado"
          },
          {
            "name": "Generador Monofasico",
            "count": 27,
            "slug": "generador-monofasico"
          },
          {
            "name": "Generador Trifasico",
            "count": 8,
            "slug": "generador-trifasico"
          },
          {
            "name": "Motosoldador",
            "count": 2,
            "slug": "motosoldador"
          }
        ]
      }
    ]
  },
  {
    "id": "jardin",
    "name": "JARDIN",
    "displayName": "Jardín",
    "description": "Herramientas de corte, poda, sopladores, pulverizadores y mantenimiento de césped.",
    "count": 287,
    "subcategoriesCount": 6,
    "subcategories": [
      {
        "name": "ACCESORIOS",
        "displayName": "Accesorios",
        "count": 21,
        "slug": "accesorios",
        "subsubcategories": [
          {
            "name": "Bolsa Recolectora",
            "count": 1,
            "slug": "bolsa-recolectora"
          },
          {
            "name": "Cercos",
            "count": 2,
            "slug": "cercos"
          },
          {
            "name": "Decoracion",
            "count": 5,
            "slug": "decoracion"
          },
          {
            "name": "Limpieza",
            "count": 8,
            "slug": "limpieza"
          },
          {
            "name": "Mango",
            "count": 5,
            "slug": "mango"
          }
        ]
      },
      {
        "name": "AGRO Y FORRAJERIA",
        "displayName": "Agro y Forrajeria",
        "count": 40,
        "slug": "agro-y-forrajeria",
        "subsubcategories": [
          {
            "name": "Fertilizantes",
            "count": 6,
            "slug": "fertilizantes"
          },
          {
            "name": "Semillas",
            "count": 34,
            "slug": "semillas"
          }
        ]
      },
      {
        "name": "HERRAMIENTAS DE CORTE Y PODA",
        "displayName": "Herramientas De Corte y Poda",
        "count": 50,
        "slug": "herramientas-de-corte-y-poda",
        "subsubcategories": [
          {
            "name": "Cortacesped Heli",
            "count": 3,
            "slug": "cortacesped-heli"
          },
          {
            "name": "Cuchillos",
            "count": 5,
            "slug": "cuchillos"
          },
          {
            "name": "Hacha",
            "count": 3,
            "slug": "hacha"
          },
          {
            "name": "Serruchos Poda",
            "count": 9,
            "slug": "serruchos-poda"
          },
          {
            "name": "Tijeras Corte Y Poda",
            "count": 30,
            "slug": "tijeras-corte-y-poda"
          }
        ]
      },
      {
        "name": "HERRAMIENTAS DE MANO",
        "displayName": "Herramientas De Mano",
        "count": 34,
        "slug": "herramientas-de-mano",
        "subsubcategories": [
          {
            "name": "Azada",
            "count": 5,
            "slug": "azada"
          },
          {
            "name": "Barrehojas",
            "count": 12,
            "slug": "barrehojas"
          },
          {
            "name": "Palas",
            "count": 7,
            "slug": "palas"
          },
          {
            "name": "Plantador",
            "count": 1,
            "slug": "plantador"
          },
          {
            "name": "Rastrillos",
            "count": 9,
            "slug": "rastrillos"
          }
        ]
      },
      {
        "name": "HERRAMIENTAS ESPECIALES",
        "displayName": "Herramientas Especiales",
        "count": 41,
        "slug": "herramientas-especiales",
        "subsubcategories": [
          {
            "name": "Escardillo",
            "count": 1,
            "slug": "escardillo"
          },
          {
            "name": "Escarificadores",
            "count": 5,
            "slug": "escarificadores"
          },
          {
            "name": "Esparcidores",
            "count": 8,
            "slug": "esparcidores"
          },
          {
            "name": "Pulverizadores",
            "count": 21,
            "slug": "pulverizadores"
          },
          {
            "name": "Recolectores Jardin",
            "count": 3,
            "slug": "recolectores-jardin"
          },
          {
            "name": "Tijeras Corte Y Poda",
            "count": 3,
            "slug": "tijeras-corte-y-poda"
          }
        ]
      },
      {
        "name": "RIEGO",
        "displayName": "Riego",
        "count": 100,
        "slug": "riego",
        "subsubcategories": [
          {
            "name": "Aspersores",
            "count": 21,
            "slug": "aspersores"
          },
          {
            "name": "Carros Y Soportes",
            "count": 8,
            "slug": "carros-y-soportes"
          },
          {
            "name": "Conectores",
            "count": 30,
            "slug": "conectores"
          },
          {
            "name": "Mangueras",
            "count": 18,
            "slug": "mangueras"
          },
          {
            "name": "Pistolas Y Lanzas",
            "count": 11,
            "slug": "pistolas-y-lanzas"
          },
          {
            "name": "Programadores",
            "count": 12,
            "slug": "programadores"
          }
        ]
      }
    ]
  },
  {
    "id": "maquina-a-bateria",
    "name": "MAQUINA A BATERIA",
    "displayName": "Máquinas a Batería",
    "description": "Línea inalámbrica profesional: motosierras, podadoras, sopladores y baterías.",
    "count": 159,
    "subcategoriesCount": 5,
    "subcategories": [
      {
        "name": "ACCESORIO",
        "displayName": "Accesorio",
        "count": 56,
        "slug": "accesorio",
        "subsubcategories": [
          {
            "name": "Barredoras",
            "count": 1,
            "slug": "barredoras"
          },
          {
            "name": "Batería",
            "count": 29,
            "slug": "bater-a"
          },
          {
            "name": "Cargador",
            "count": 26,
            "slug": "cargador"
          }
        ]
      },
      {
        "name": "FORESTAL Y PODA",
        "displayName": "Forestal y Poda",
        "count": 26,
        "slug": "forestal-y-poda",
        "subsubcategories": [
          {
            "name": "Motosierra",
            "count": 23,
            "slug": "motosierra"
          },
          {
            "name": "Podadora De Altura",
            "count": 3,
            "slug": "podadora-de-altura"
          }
        ]
      },
      {
        "name": "JARDIN",
        "displayName": "Jardin",
        "count": 49,
        "slug": "jardin",
        "subsubcategories": [
          {
            "name": "Automower (Robot Cortacésped)",
            "count": 5,
            "slug": "automower-robot-cortac-sped"
          },
          {
            "name": "Bordeadora",
            "count": 10,
            "slug": "bordeadora"
          },
          {
            "name": "Cortacésped",
            "count": 7,
            "slug": "cortac-sped"
          },
          {
            "name": "Desmalezadora",
            "count": 4,
            "slug": "desmalezadora"
          },
          {
            "name": "Multiherramienta",
            "count": 1,
            "slug": "multiherramienta"
          },
          {
            "name": "Pulverizador",
            "count": 6,
            "slug": "pulverizador"
          },
          {
            "name": "Soplador",
            "count": 16,
            "slug": "soplador"
          }
        ]
      },
      {
        "name": "LIMPIEZA",
        "displayName": "Limpieza",
        "count": 12,
        "slug": "limpieza",
        "subsubcategories": [
          {
            "name": "Aspiradora Bateria",
            "count": 6,
            "slug": "aspiradora-bateria"
          },
          {
            "name": "Barredoras",
            "count": 4,
            "slug": "barredoras"
          },
          {
            "name": "Hidrolavadora",
            "count": 1,
            "slug": "hidrolavadora"
          },
          {
            "name": "Limpiador Ventanas",
            "count": 1,
            "slug": "limpiador-ventanas"
          }
        ]
      },
      {
        "name": "PODA",
        "displayName": "Poda",
        "count": 16,
        "slug": "poda",
        "subsubcategories": [
          {
            "name": "Cortacerco",
            "count": 13,
            "slug": "cortacerco"
          },
          {
            "name": "Tijera Poda",
            "count": 3,
            "slug": "tijera-poda"
          }
        ]
      }
    ]
  },
  {
    "id": "maquina-a-explosion",
    "name": "MAQUINA A EXPLOSION",
    "displayName": "Máquinas a Explosión",
    "description": "Motosierras, motoguadañas, cortacéspedes, riders y motores nafteros o diesel.",
    "count": 265,
    "subcategoriesCount": 8,
    "subcategories": [
      {
        "name": "ACCESORIOS",
        "displayName": "Accesorios",
        "count": 14,
        "slug": "accesorios",
        "subsubcategories": [
          {
            "name": "Bolsa Recolectora",
            "count": 6,
            "slug": "bolsa-recolectora"
          },
          {
            "name": "Carro Recolector",
            "count": 3,
            "slug": "carro-recolector"
          },
          {
            "name": "Cepillo Recolector",
            "count": 3,
            "slug": "cepillo-recolector"
          },
          {
            "name": "Hoyadoras",
            "count": 2,
            "slug": "hoyadoras"
          }
        ]
      },
      {
        "name": "AGRO Y FORRAJERIA",
        "displayName": "Agro y Forrajeria",
        "count": 7,
        "slug": "agro-y-forrajeria",
        "subsubcategories": [
          {
            "name": "Motocultivador",
            "count": 7,
            "slug": "motocultivador"
          }
        ]
      },
      {
        "name": "AGUA",
        "displayName": "Agua",
        "count": 26,
        "slug": "agua",
        "subsubcategories": [
          {
            "name": "Motobomba Diesel",
            "count": 1,
            "slug": "motobomba-diesel"
          },
          {
            "name": "Motobomba Naftera",
            "count": 25,
            "slug": "motobomba-naftera"
          }
        ]
      },
      {
        "name": "FORESTAL Y PODA",
        "displayName": "Forestal y Poda",
        "count": 42,
        "slug": "forestal-y-poda",
        "subsubcategories": [
          {
            "name": "Motosierra",
            "count": 37,
            "slug": "motosierra"
          },
          {
            "name": "Podadora Altura",
            "count": 5,
            "slug": "podadora-altura"
          }
        ]
      },
      {
        "name": "JARDIN",
        "displayName": "Jardin",
        "count": 150,
        "slug": "jardin",
        "subsubcategories": [
          {
            "name": "Ahoyadora",
            "count": 7,
            "slug": "ahoyadora"
          },
          {
            "name": "Bordeadora",
            "count": 4,
            "slug": "bordeadora"
          },
          {
            "name": "Carpidoras",
            "count": 1,
            "slug": "carpidoras"
          },
          {
            "name": "Cortacesped",
            "count": 39,
            "slug": "cortacesped"
          },
          {
            "name": "Desmalezadora",
            "count": 35,
            "slug": "desmalezadora"
          },
          {
            "name": "Fumigador",
            "count": 7,
            "slug": "fumigador"
          },
          {
            "name": "Herramienta Multiuso",
            "count": 12,
            "slug": "herramienta-multiuso"
          },
          {
            "name": "Mototaladro",
            "count": 3,
            "slug": "mototaladro"
          },
          {
            "name": "Pulverizador",
            "count": 7,
            "slug": "pulverizador"
          },
          {
            "name": "Radio Cero",
            "count": 8,
            "slug": "radio-cero"
          },
          {
            "name": "Riders",
            "count": 4,
            "slug": "riders"
          },
          {
            "name": "Soplador",
            "count": 15,
            "slug": "soplador"
          },
          {
            "name": "Tractor",
            "count": 8,
            "slug": "tractor"
          }
        ]
      },
      {
        "name": "LIMPIEZA",
        "displayName": "Limpieza",
        "count": 5,
        "slug": "limpieza",
        "subsubcategories": [
          {
            "name": "Hidrolavadoras A Explosion",
            "count": 5,
            "slug": "hidrolavadoras-a-explosion"
          }
        ]
      },
      {
        "name": "PODA",
        "displayName": "Poda",
        "count": 9,
        "slug": "poda",
        "subsubcategories": [
          {
            "name": "Cortacerco",
            "count": 9,
            "slug": "cortacerco"
          }
        ]
      },
      {
        "name": "REDUCCION RESIDUOS ORGANICOS",
        "displayName": "Reduccion Residuos Organicos",
        "count": 12,
        "slug": "reduccion-residuos-organicos",
        "subsubcategories": [
          {
            "name": "Chipeadora",
            "count": 12,
            "slug": "chipeadora"
          }
        ]
      }
    ]
  },
  {
    "id": "maquina-electrica",
    "name": "MAQUINA ELECTRICA",
    "displayName": "Máquinas Eléctricas",
    "description": "Hidrolavadoras industriales, aspiradoras profesionales y lavadoras de piso.",
    "count": 108,
    "subcategoriesCount": 6,
    "subcategories": [
      {
        "name": "ACCESORIOS E INSUMOS",
        "displayName": "Accesorios e Insumos",
        "count": 28,
        "slug": "accesorios-e-insumos",
        "subsubcategories": [
          {
            "name": "Aspiradoras",
            "count": 6,
            "slug": "aspiradoras"
          },
          {
            "name": "Lavadoras",
            "count": 2,
            "slug": "lavadoras"
          },
          {
            "name": "Lustradoras",
            "count": 20,
            "slug": "lustradoras"
          }
        ]
      },
      {
        "name": "AGRO Y FORRAJERIA",
        "displayName": "Agro y Forrajeria",
        "count": 1,
        "slug": "agro-y-forrajeria",
        "subsubcategories": [
          {
            "name": "Trituradora",
            "count": 1,
            "slug": "trituradora"
          }
        ]
      },
      {
        "name": "FORESTAL Y PODA",
        "displayName": "Forestal y Poda",
        "count": 2,
        "slug": "forestal-y-poda",
        "subsubcategories": [
          {
            "name": "Motosierra",
            "count": 1,
            "slug": "motosierra"
          },
          {
            "name": "Motosierras",
            "count": 1,
            "slug": "motosierras"
          }
        ]
      },
      {
        "name": "JARDIN",
        "displayName": "Jardin",
        "count": 10,
        "slug": "jardin",
        "subsubcategories": [
          {
            "name": "Bordeadora",
            "count": 1,
            "slug": "bordeadora"
          },
          {
            "name": "Cortacesped",
            "count": 5,
            "slug": "cortacesped"
          },
          {
            "name": "Soplador",
            "count": 4,
            "slug": "soplador"
          }
        ]
      },
      {
        "name": "LIMPIEZA",
        "displayName": "Limpieza",
        "count": 65,
        "slug": "limpieza",
        "subsubcategories": [
          {
            "name": "Aspiradora Electrica",
            "count": 32,
            "slug": "aspiradora-electrica"
          },
          {
            "name": "Hidrolavadoras Electricas",
            "count": 26,
            "slug": "hidrolavadoras-electricas"
          },
          {
            "name": "Lavadoras",
            "count": 1,
            "slug": "lavadoras"
          },
          {
            "name": "Lustradoras",
            "count": 6,
            "slug": "lustradoras"
          }
        ]
      },
      {
        "name": "PODA",
        "displayName": "Poda",
        "count": 2,
        "slug": "poda",
        "subsubcategories": [
          {
            "name": "Cortacerco",
            "count": 2,
            "slug": "cortacerco"
          }
        ]
      }
    ]
  },
  {
    "id": "maquina-manual",
    "name": "MAQUINA MANUAL",
    "displayName": "Máquinas Manuales",
    "description": "Barredoras mecánicas y equipos de limpieza manual para taller y depósito.",
    "count": 8,
    "subcategoriesCount": 1,
    "subcategories": [
      {
        "name": "LIMPIEZA",
        "displayName": "Limpieza",
        "count": 8,
        "slug": "limpieza",
        "subsubcategories": [
          {
            "name": "Accesorios De Limpieza",
            "count": 6,
            "slug": "accesorios-de-limpieza"
          },
          {
            "name": "Barredora",
            "count": 2,
            "slug": "barredora"
          }
        ]
      }
    ]
  },
  {
    "id": "producto-de-fuerza",
    "name": "PRODUCTO DE FUERZA",
    "displayName": "Productos de Fuerza",
    "description": "Motores estacionarios horizontales y verticales, diesel y motobombas pesadas.",
    "count": 96,
    "subcategoriesCount": 2,
    "subcategories": [
      {
        "name": "GENERADOR",
        "displayName": "Generador",
        "count": 6,
        "slug": "generador",
        "subsubcategories": [
          {
            "name": "Grupo Electrogenos",
            "count": 6,
            "slug": "grupo-electrogenos"
          }
        ]
      },
      {
        "name": "MOTOR EXPLOSION",
        "displayName": "Motor Explosion",
        "count": 90,
        "slug": "motor-explosion",
        "subsubcategories": [
          {
            "name": "Motor Diesel",
            "count": 3,
            "slug": "motor-diesel"
          },
          {
            "name": "Motor Horizontal",
            "count": 63,
            "slug": "motor-horizontal"
          },
          {
            "name": "Motor Vertical",
            "count": 24,
            "slug": "motor-vertical"
          }
        ]
      }
    ]
  },
  {
    "id": "repuestos",
    "name": "REPUESTOS",
    "displayName": "Repuestos",
    "description": "Componentes originales, carburadores, cilindros, cuchillas y kits de reparación.",
    "count": 563,
    "subcategoriesCount": 15,
    "subcategories": [
      {
        "name": "CARBURADOR",
        "displayName": "Carburador",
        "count": 17,
        "slug": "carburador",
        "subsubcategories": [
          {
            "name": "Bombin",
            "count": 1,
            "slug": "bombin"
          },
          {
            "name": "Eje Acelerador",
            "count": 1,
            "slug": "eje-acelerador"
          },
          {
            "name": "Flotante",
            "count": 1,
            "slug": "flotante"
          },
          {
            "name": "Junta",
            "count": 1,
            "slug": "junta"
          },
          {
            "name": "Kit Aguja",
            "count": 2,
            "slug": "kit-aguja"
          },
          {
            "name": "Kit Diafragmas",
            "count": 10,
            "slug": "kit-diafragmas"
          },
          {
            "name": "Kit Reparacion",
            "count": 1,
            "slug": "kit-reparacion"
          }
        ]
      },
      {
        "name": "COMPRESOR",
        "displayName": "Compresor",
        "count": 8,
        "slug": "compresor",
        "subsubcategories": [
          {
            "name": "Interruptor",
            "count": 1,
            "slug": "interruptor"
          },
          {
            "name": "Manguera Alta Presion",
            "count": 3,
            "slug": "manguera-alta-presion"
          },
          {
            "name": "Rueda",
            "count": 4,
            "slug": "rueda"
          }
        ]
      },
      {
        "name": "CONSUMIBLE",
        "displayName": "Consumible",
        "count": 2,
        "slug": "consumible",
        "subsubcategories": [
          {
            "name": "Manguera Combustible",
            "count": 1,
            "slug": "manguera-combustible"
          },
          {
            "name": "Soga Arranque",
            "count": 1,
            "slug": "soga-arranque"
          }
        ]
      },
      {
        "name": "CORTACESPED",
        "displayName": "Cortacesped",
        "count": 21,
        "slug": "cortacesped",
        "subsubcategories": [
          {
            "name": "Adaptador Cuchilla",
            "count": 4,
            "slug": "adaptador-cuchilla"
          },
          {
            "name": "Cable Y Palanca",
            "count": 1,
            "slug": "cable-y-palanca"
          },
          {
            "name": "Cuchilla",
            "count": 8,
            "slug": "cuchilla"
          },
          {
            "name": "Rueda",
            "count": 8,
            "slug": "rueda"
          }
        ]
      },
      {
        "name": "DESMALEZADORA",
        "displayName": "Desmalezadora",
        "count": 38,
        "slug": "desmalezadora",
        "subsubcategories": [
          {
            "name": "Acelerador",
            "count": 1,
            "slug": "acelerador"
          },
          {
            "name": "Aro Piston",
            "count": 4,
            "slug": "aro-piston"
          },
          {
            "name": "Bobina Encendido",
            "count": 3,
            "slug": "bobina-encendido"
          },
          {
            "name": "Cabezal",
            "count": 3,
            "slug": "cabezal"
          },
          {
            "name": "Carburador",
            "count": 7,
            "slug": "carburador"
          },
          {
            "name": "Cardan",
            "count": 2,
            "slug": "cardan"
          },
          {
            "name": "Cilindro",
            "count": 5,
            "slug": "cilindro"
          },
          {
            "name": "Cuchilla",
            "count": 7,
            "slug": "cuchilla"
          },
          {
            "name": "Filtro Aire",
            "count": 1,
            "slug": "filtro-aire"
          },
          {
            "name": "Kit Juntas Diafragma",
            "count": 2,
            "slug": "kit-juntas-diafragma"
          },
          {
            "name": "Piston Completo",
            "count": 1,
            "slug": "piston-completo"
          },
          {
            "name": "Reten",
            "count": 1,
            "slug": "reten"
          },
          {
            "name": "Tapa Arranque",
            "count": 1,
            "slug": "tapa-arranque"
          }
        ]
      },
      {
        "name": "LUSTRADORAS",
        "displayName": "Lustradoras",
        "count": 7,
        "slug": "lustradoras",
        "subsubcategories": [
          {
            "name": "Lustradoras Super Speed",
            "count": 7,
            "slug": "lustradoras-super-speed"
          }
        ]
      },
      {
        "name": "MOTOR",
        "displayName": "Motor",
        "count": 103,
        "slug": "motor",
        "subsubcategories": [
          {
            "name": "Aro Piston",
            "count": 2,
            "slug": "aro-piston"
          },
          {
            "name": "Bateria Libre Mantenimiento",
            "count": 12,
            "slug": "bateria-libre-mantenimiento"
          },
          {
            "name": "Bobina Encendido",
            "count": 5,
            "slug": "bobina-encendido"
          },
          {
            "name": "Bomba Nafta",
            "count": 1,
            "slug": "bomba-nafta"
          },
          {
            "name": "Bujia",
            "count": 9,
            "slug": "bujia"
          },
          {
            "name": "Cable Bateria",
            "count": 2,
            "slug": "cable-bateria"
          },
          {
            "name": "Carburador",
            "count": 3,
            "slug": "carburador"
          },
          {
            "name": "Coronas De Arranque",
            "count": 1,
            "slug": "coronas-de-arranque"
          },
          {
            "name": "Diafragma",
            "count": 4,
            "slug": "diafragma"
          },
          {
            "name": "Embrague",
            "count": 2,
            "slug": "embrague"
          },
          {
            "name": "Filtro Aceite",
            "count": 3,
            "slug": "filtro-aceite"
          },
          {
            "name": "Filtro Aire",
            "count": 34,
            "slug": "filtro-aire"
          },
          {
            "name": "Filtro Combustible",
            "count": 6,
            "slug": "filtro-combustible"
          },
          {
            "name": "Junta",
            "count": 3,
            "slug": "junta"
          },
          {
            "name": "Llave Paso",
            "count": 2,
            "slug": "llave-paso"
          },
          {
            "name": "Modulo Encendido",
            "count": 1,
            "slug": "modulo-encendido"
          },
          {
            "name": "Motor Arranque",
            "count": 3,
            "slug": "motor-arranque"
          },
          {
            "name": "Polea",
            "count": 1,
            "slug": "polea"
          },
          {
            "name": "Pre Filtro",
            "count": 3,
            "slug": "pre-filtro"
          },
          {
            "name": "Regulador Voltaje",
            "count": 1,
            "slug": "regulador-voltaje"
          },
          {
            "name": "Resorte",
            "count": 1,
            "slug": "resorte"
          },
          {
            "name": "Reten",
            "count": 1,
            "slug": "reten"
          },
          {
            "name": "Solenoide",
            "count": 2,
            "slug": "solenoide"
          },
          {
            "name": "Tapa Tanque",
            "count": 1,
            "slug": "tapa-tanque"
          }
        ]
      },
      {
        "name": "MOTOR VERTICAL",
        "displayName": "Motor Vertical",
        "count": 4,
        "slug": "motor-vertical",
        "subsubcategories": [
          {
            "name": "Filtro Aire",
            "count": 1,
            "slug": "filtro-aire"
          },
          {
            "name": "Junta Carter",
            "count": 1,
            "slug": "junta-carter"
          },
          {
            "name": "Polea De Arranque",
            "count": 1,
            "slug": "polea-de-arranque"
          },
          {
            "name": "Pre Filtro",
            "count": 1,
            "slug": "pre-filtro"
          }
        ]
      },
      {
        "name": "MOTOSIERRA",
        "displayName": "Motosierra",
        "count": 153,
        "slug": "motosierra",
        "subsubcategories": [
          {
            "name": "Anillo",
            "count": 5,
            "slug": "anillo"
          },
          {
            "name": "Arandela",
            "count": 1,
            "slug": "arandela"
          },
          {
            "name": "Aro Piston",
            "count": 8,
            "slug": "aro-piston"
          },
          {
            "name": "Barra",
            "count": 57,
            "slug": "barra"
          },
          {
            "name": "Bomba Aceite",
            "count": 1,
            "slug": "bomba-aceite"
          },
          {
            "name": "Campana Embrague",
            "count": 1,
            "slug": "campana-embrague"
          },
          {
            "name": "Carburador",
            "count": 6,
            "slug": "carburador"
          },
          {
            "name": "Cilindro",
            "count": 10,
            "slug": "cilindro"
          },
          {
            "name": "Cta Paso",
            "count": 21,
            "slug": "cta-paso"
          },
          {
            "name": "Embrague",
            "count": 2,
            "slug": "embrague"
          },
          {
            "name": "Filtro Aire",
            "count": 3,
            "slug": "filtro-aire"
          },
          {
            "name": "Garganta Admision",
            "count": 1,
            "slug": "garganta-admision"
          },
          {
            "name": "Graseras",
            "count": 1,
            "slug": "graseras"
          },
          {
            "name": "Junta",
            "count": 1,
            "slug": "junta"
          },
          {
            "name": "Kit Juntas Diafragma",
            "count": 2,
            "slug": "kit-juntas-diafragma"
          },
          {
            "name": "Kit Reparacion",
            "count": 1,
            "slug": "kit-reparacion"
          },
          {
            "name": "Manguera",
            "count": 4,
            "slug": "manguera"
          },
          {
            "name": "Modulo Encendido",
            "count": 1,
            "slug": "modulo-encendido"
          },
          {
            "name": "Piston",
            "count": 1,
            "slug": "piston"
          },
          {
            "name": "Piston Completo",
            "count": 9,
            "slug": "piston-completo"
          },
          {
            "name": "Piñon",
            "count": 11,
            "slug": "pi-on"
          },
          {
            "name": "Reten",
            "count": 3,
            "slug": "reten"
          },
          {
            "name": "Tapa Arranque Completa",
            "count": 1,
            "slug": "tapa-arranque-completa"
          },
          {
            "name": "Trinquete",
            "count": 1,
            "slug": "trinquete"
          },
          {
            "name": "Tuerca",
            "count": 1,
            "slug": "tuerca"
          }
        ]
      },
      {
        "name": "PULVERIZADOR",
        "displayName": "Pulverizador",
        "count": 14,
        "slug": "pulverizador",
        "subsubcategories": [
          {
            "name": "Pulverizador Giber",
            "count": 14,
            "slug": "pulverizador-giber"
          }
        ]
      },
      {
        "name": "REMACHADORA",
        "displayName": "Remachadora",
        "count": 1,
        "slug": "remachadora",
        "subsubcategories": [
          {
            "name": "Pastilla",
            "count": 1,
            "slug": "pastilla"
          }
        ]
      },
      {
        "name": "SOPLADOR",
        "displayName": "Soplador",
        "count": 1,
        "slug": "soplador",
        "subsubcategories": [
          {
            "name": "Carburador",
            "count": 1,
            "slug": "carburador"
          }
        ]
      },
      {
        "name": "TERMO",
        "displayName": "Termo",
        "count": 3,
        "slug": "termo",
        "subsubcategories": [
          {
            "name": "Pico",
            "count": 3,
            "slug": "pico"
          }
        ]
      },
      {
        "name": "TRACTOR",
        "displayName": "Tractor",
        "count": 189,
        "slug": "tractor",
        "subsubcategories": [
          {
            "name": "Adaptador Cuchilla",
            "count": 1,
            "slug": "adaptador-cuchilla"
          },
          {
            "name": "Brazo Elevacion",
            "count": 1,
            "slug": "brazo-elevacion"
          },
          {
            "name": "Buje",
            "count": 12,
            "slug": "buje"
          },
          {
            "name": "Bulon",
            "count": 2,
            "slug": "bulon"
          },
          {
            "name": "Cable Acelerador",
            "count": 2,
            "slug": "cable-acelerador"
          },
          {
            "name": "Camara",
            "count": 7,
            "slug": "camara"
          },
          {
            "name": "Carcasa Torreta",
            "count": 5,
            "slug": "carcasa-torreta"
          },
          {
            "name": "Correa",
            "count": 40,
            "slug": "correa"
          },
          {
            "name": "Cubierta",
            "count": 9,
            "slug": "cubierta"
          },
          {
            "name": "Cuchilla",
            "count": 45,
            "slug": "cuchilla"
          },
          {
            "name": "Eje Direccion",
            "count": 1,
            "slug": "eje-direccion"
          },
          {
            "name": "Eje Torreta",
            "count": 8,
            "slug": "eje-torreta"
          },
          {
            "name": "Interruptor",
            "count": 1,
            "slug": "interruptor"
          },
          {
            "name": "Llave Arranque",
            "count": 1,
            "slug": "llave-arranque"
          },
          {
            "name": "Polea",
            "count": 8,
            "slug": "polea"
          },
          {
            "name": "Polea Motor",
            "count": 2,
            "slug": "polea-motor"
          },
          {
            "name": "Polea Tensora",
            "count": 13,
            "slug": "polea-tensora"
          },
          {
            "name": "Pulsador",
            "count": 2,
            "slug": "pulsador"
          },
          {
            "name": "Rotula",
            "count": 5,
            "slug": "rotula"
          },
          {
            "name": "Rueda Copiadora",
            "count": 1,
            "slug": "rueda-copiadora"
          },
          {
            "name": "Rueda Niveladora",
            "count": 1,
            "slug": "rueda-niveladora"
          },
          {
            "name": "Tambor Arranque",
            "count": 5,
            "slug": "tambor-arranque"
          },
          {
            "name": "Tornillo",
            "count": 1,
            "slug": "tornillo"
          },
          {
            "name": "Torreta",
            "count": 12,
            "slug": "torreta"
          },
          {
            "name": "Transmision",
            "count": 1,
            "slug": "transmision"
          },
          {
            "name": "Tuerca",
            "count": 2,
            "slug": "tuerca"
          },
          {
            "name": "Valvula",
            "count": 1,
            "slug": "valvula"
          }
        ]
      },
      {
        "name": "UNIVERSAL",
        "displayName": "Universal",
        "count": 2,
        "slug": "universal",
        "subsubcategories": [
          {
            "name": "Kit Juntas Diafragma",
            "count": 2,
            "slug": "kit-juntas-diafragma"
          }
        ]
      }
    ]
  },
  {
    "id": "riego",
    "name": "RIEGO",
    "displayName": "Riego",
    "description": "Aspersores, toberas, electroválvulas, goteros, caños y accesorios de polietileno.",
    "count": 200,
    "subcategoriesCount": 3,
    "subcategories": [
      {
        "name": "ACCESORIO",
        "displayName": "Accesorio",
        "count": 163,
        "slug": "accesorio",
        "subsubcategories": [
          {
            "name": "Acople",
            "count": 6,
            "slug": "acople"
          },
          {
            "name": "Adaptador",
            "count": 1,
            "slug": "adaptador"
          },
          {
            "name": "Aspersor",
            "count": 1,
            "slug": "aspersor"
          },
          {
            "name": "Buje Red",
            "count": 10,
            "slug": "buje-red"
          },
          {
            "name": "Canilla",
            "count": 1,
            "slug": "canilla"
          },
          {
            "name": "Codo",
            "count": 21,
            "slug": "codo"
          },
          {
            "name": "Cupla",
            "count": 8,
            "slug": "cupla"
          },
          {
            "name": "Curva",
            "count": 6,
            "slug": "curva"
          },
          {
            "name": "Espiga",
            "count": 18,
            "slug": "espiga"
          },
          {
            "name": "Estaca",
            "count": 1,
            "slug": "estaca"
          },
          {
            "name": "Filtros",
            "count": 1,
            "slug": "filtros"
          },
          {
            "name": "Goteros",
            "count": 7,
            "slug": "goteros"
          },
          {
            "name": "Kit",
            "count": 1,
            "slug": "kit"
          },
          {
            "name": "Niple",
            "count": 12,
            "slug": "niple"
          },
          {
            "name": "Reparadores De Mangueras",
            "count": 1,
            "slug": "reparadores-de-mangueras"
          },
          {
            "name": "Rosca Con Tuerca",
            "count": 7,
            "slug": "rosca-con-tuerca"
          },
          {
            "name": "Tapon",
            "count": 12,
            "slug": "tapon"
          },
          {
            "name": "Tee",
            "count": 20,
            "slug": "tee"
          },
          {
            "name": "Union Doble",
            "count": 7,
            "slug": "union-doble"
          },
          {
            "name": "Valvula",
            "count": 3,
            "slug": "valvula"
          },
          {
            "name": "Valvula Esf Pvc",
            "count": 9,
            "slug": "valvula-esf-pvc"
          },
          {
            "name": "Valvula Esferica Metal",
            "count": 10,
            "slug": "valvula-esferica-metal"
          }
        ]
      },
      {
        "name": "CAÑOS Y MANGUERAS",
        "displayName": "Caños y Mangueras",
        "count": 29,
        "slug": "ca-os-y-mangueras",
        "subsubcategories": [
          {
            "name": "Caño Polietileno",
            "count": 9,
            "slug": "ca-o-polietileno"
          },
          {
            "name": "Caño Polipropileno",
            "count": 8,
            "slug": "ca-o-polipropileno"
          },
          {
            "name": "Mangueras",
            "count": 12,
            "slug": "mangueras"
          }
        ]
      },
      {
        "name": "CONSUMIBLE RIEGO",
        "displayName": "Consumible Riego",
        "count": 8,
        "slug": "consumible-riego",
        "subsubcategories": [
          {
            "name": "Adhesivo",
            "count": 2,
            "slug": "adhesivo"
          },
          {
            "name": "Sellarosca",
            "count": 3,
            "slug": "sellarosca"
          },
          {
            "name": "Teflon",
            "count": 3,
            "slug": "teflon"
          }
        ]
      }
    ]
  }
];

if (typeof window !== 'undefined') {
  window.REAL_CATEGORIES_TREE = REAL_CATEGORIES_TREE;
}
